### ISSUE TITLE
fastqc-gtz error

### ISSUE THREAD

**Issue by JingzhX** [Genetalks/gtz#17]
Hi,

Always got the following errors when trying to run on *.fq.gtz files:

> "ERROR:Error: test.1.fq.gtz format error!(magic num error)
> Started analysis of test.1.fq.gtz
> Please waiting...
> Analysis complete for test.1.fq.gtz
> Failed to process file test.1.fq.gtz
> java.lang.ArrayIndexOutOfBoundsException: -1
>         at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
>         at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
>         at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
>         at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
>         at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
>         at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
>         at java.lang.Thread.run(Thread.java:748)

The gtz is able to decompress gtz files. 

Any solutions? Thank you.

Jim

**Comment by bolunfeng** [comment]
sorry for the late reply. Please confirm if you can extract this file with gtz .(gtz version:2.1.2)
